---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-files
  labels:
    io.kompose.service: backend-files
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logos
  labels:
    io.kompose.service: logos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backgrounds
  labels:
    io.kompose.service: backgrounds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
