apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- storage.yaml
- backend-config.yaml
- backend-sealed-secret.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml

images:
- name: abc.docker-registry.gewis.nl/crm/parelpracht/client
  newTag: 1.5.0
- name: abc.docker-registry.gewis.nl/crm/parelpracht/server
  newTag: 1.5.0
