export enum DocumentStatus {
  CREATED = 'CREATED',
  SENT = 'SENT',
  PAID = 'PAID',
  PROPOSED = 'PROPOSED',
  CONFIRMED = 'CONFIRMED',
  FINISHED = 'FINISHED',
  IRRECOVERABLE = 'IRRECOVERABLE',
  CANCELLED = 'CANCELLED',
  NOTDELIVERED = 'NOTDELIVERED',
  DELIVERED = 'DELIVERED',
  DEFERRED = 'DEFERRED',
}
