apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "80"
  SERVER_HOST: "https://parelpracht.test.gewis.nl"
  USE_HTTPS: "true"
  TZ: "Europe/Amsterdam"

  # LDAP
  LDAP_URL: "ldaps://ldaps.gewis.nl"
  LDAP_BINDDN: "CN=Serviceaccount parelpracht.gewis.nl webapplicatie,CN=Managed Service Accounts,DC=gewiswg,DC=gewis,DC=nl"
  LDAP_SEARCHBASE: "OU=Member accounts,DC=gewiswg,DC=gewis,DC=nl"
  LDAP_SEARCHFILTER: "(sAMAccountName={{username}})"

  # Mail
  MAIL_HOST: "smtp.gewis.nl"
  MAIL_PORT: "465"
  MAIL_USER: "service-pptest@gewis.nl"
  MAIL_FROM: "ParelPracht Test Environment <service-pptest@gewis.nl>"

  # Database (TypeORM)
  TYPEORM_CONNECTION: "mariadb"
  TYPEORM_HOST: "mariadb01.db.gewis.nl"
  TYPEORM_PORT: "3306"
  TYPEORM_DATABASE: "parelpracht_test"
  TYPEORM_USERNAME: "service-pptest"
  TYPEORM_SSL_ENABLED: "true"
  TYPEORM_SSL_CACERTS: "/etc/ssl/certs/ca-certificates.crt"
  TYPEORM_SYNCHRONIZE: "true"
  TYPEORM_LOGGING: "false"
  TYPEORM_ENTITIES: "dist/entity/**/*.js"
  TYPEORM_MIGRATIONS: "dist/migration/**/*.js"
  TYPEORM_SUBSCRIBERS: "dist/subscriber/**/*.js"
