apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parelpracht-test

resources:
- ../base
- backend-config.yaml
- backend-sealed-secret.yaml
- ingress.yaml

images:
- digest: sha256:8c19d95b430eb03a6fbbd9e187753f58d674db42c71d107b282b9e2aeb20712d
  name: abc.docker-registry.gewis.nl/crm/parelpracht/client
- digest: sha256:85d0ed245e1eb1f49d0f2fc6a8896fe128c3cbd1614925d9771e12486b689c47
  name: abc.docker-registry.gewis.nl/crm/parelpracht/server
