apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parelpracht-test

resources:
- ../base
- backend-config.yaml
- backend-sealed-secret.yaml
- ingress.yaml

images:
- digest: sha256:2820abf584dfae151b805fffccb3ce5f2d629d9ebe1c5583a710f3c6f5eb28e5
  name: abc.docker-registry.gewis.nl/crm/parelpracht/client
- digest: sha256:bcac2a9965cdb9863402c7f1a974204a9d30e25103e5527fdd00a032d507cdc5
  name: abc.docker-registry.gewis.nl/crm/parelpracht/server
