name: Build and push Docker image
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and push Docker image
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: build and push
        uses: docker/build-push-action@v1
        with:
          context: .
          dockerfile: Dockerfile
          push: true
      - uses: docker/push-action@v1
        with:
          repository: parelpracht.docker-registry.gewis.nl/parelpracht-client:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

