name: Lint and build (server)

on:
  push:
    branches:
      - main
      - develop
    paths:
      - parelpracht-server
  pull_request:
    branches:
      - main
      - develop
    paths:
      - parelpracht-server

jobs:
  build-and-lint:
    uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
    with:
      node-version: "22.x"
      lint: true
      format: false
      build: true
      working-directory: parelpracht-server
