name: Semantic release

on:
  push:
    branches:
      - develop

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  release:
    uses: GEWIS/actions/.github/workflows/docker-release.yml@0afd41a8f1a0e9342f7edffa71cac0a286f15135
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      projects: "['parelpracht-client', 'parelpracht-server']"
      version: ${{ needs.versioning.outputs.next-version }}
      docker-registry: 'abc.docker-registry.gewis.nl'
      docker-paths: "['crm/parelpracht']"
      github-registry: 'false'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_PARELPRACHT_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_PARELPRACHT_PWD }}
